# Site settings
title: Blog | thoughtram - Extend your memory
email: hello@thoughtram.io
author: thoughtram UG
description: "We are thoughtram. We enjoy learning new stuff every day and we love teaching it to others even more."
baseurl: ""
url: "http://blog.thoughtram.io/"
google_analytics: "UA-51360648-2"
animated: false
show_related_posts: false

# Build settings
markdown: kramdown
paginate: 5
sass:
  compressed: true
